// apps/frontend/src/lib/components/ProfileHeader.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import { Settings } from '@lucide/svelte';
  import { imageUrl } from '$lib/utils/imageUrl';
  import { pluralize } from '$lib/utils/pluralize';
  import type { User } from '$lib/types';

  let {
    profileUser = $bindable(),
    isCurrentUser,
    isFollowPending = $bindable(false)
  }: {
    profileUser: User;
    isCurrentUser: boolean;
    isFollowPending?: boolean;
  } = $props();
</script>

<div class="flex w-full flex-col items-center gap-6 rounded-2xl border border-base-300 bg-base-100 p-6 text-base-content shadow-lg shadow-slate-900/5 sm:px-8 md:flex-row md:items-start">
  <div class="relative h-24 w-24 shrink-0 overflow-hidden rounded-full border border-base-300 shadow-md sm:h-28 sm:w-28">
    <img class="h-full w-full object-cover" src={imageUrl(profileUser.avatar)} alt={profileUser.username} />
  </div>

  <div class="flex w-full flex-grow flex-col gap-4 text-center md:text-left">
    <div class="flex w-full flex-col items-center gap-4 sm:flex-row sm:items-start sm:justify-between sm:text-left">
      <div class="grid min-w-0 gap-1">
        <h1 class="break-words text-2xl font-black tracking-tight text-base-content sm:text-3xl">
          {profileUser.name || profileUser.username}
        </h1>
        <p class="break-words text-sm font-bold text-base-content/60">@{profileUser.username}</p>
      </div>

      {#if isCurrentUser}
        <a
          href="/settings"
          class="btn btn-neutral btn-sm h-10 min-h-10 shrink-0 gap-2 rounded-full px-5 font-extrabold shadow-md shadow-slate-900/15"
        >
          <Settings class="h-4 w-4" />
          Settings
        </a>
      {:else}
        <form
          method="POST"
          action={profileUser.isFollowing ? '?/unfollow' : '?/follow'}
          use:enhance={() => {
            isFollowPending = true;
            const wasFollowing = profileUser.isFollowing;
            profileUser = { ...profileUser, isFollowing: !wasFollowing, followers: profileUser.followers + (wasFollowing ? -1 : 1) };
            return async ({ result }) => {
              isFollowPending = false;
              if (result.type === 'error' || result.type === 'failure') {
                profileUser = { ...profileUser, isFollowing: wasFollowing, followers: profileUser.followers + (wasFollowing ? 1 : -1) };
              }
            };
          }}
        >
          <button
            type="submit"
            disabled={isFollowPending}
            class="btn btn-sm h-10 min-h-10 shrink-0 gap-2 rounded-full px-5 font-extrabold shadow-md shadow-slate-900/15 {profileUser.isFollowing ? 'btn-outline' : 'btn-neutral'}"
          >
            {profileUser.isFollowing ? 'Unfollow' : 'Follow'}
          </button>
        </form>
      {/if}
    </div>

    {#if profileUser.bio}
      <p class="w-full max-w-xl whitespace-pre-wrap text-sm leading-relaxed text-base-content/70">
        {profileUser.bio}
      </p>
    {/if}

    <div class="flex items-center justify-center gap-6 text-sm font-bold text-base-content/70 md:justify-start">
      <a href="/@{profileUser.username}" class="transition-colors hover:text-base-content">
        <strong class="font-black text-base-content">{profileUser.posts}</strong> {pluralize(profileUser.posts, 'post')}
      </a>
      <a href="/@{profileUser.username}/likes" class="transition-colors hover:text-base-content">
        <strong class="font-black text-base-content">{profileUser.likes}</strong> {pluralize(profileUser.likes, 'like')}
      </a>
      <a href="/@{profileUser.username}/followers" class="transition-colors hover:text-base-content">
        <strong class="font-black text-base-content">{profileUser.followers}</strong> {pluralize(profileUser.followers, 'follower')}
      </a>
      <a href="/@{profileUser.username}/following" class="transition-colors hover:text-base-content">
        <strong class="font-black text-base-content">{profileUser.following}</strong> following
      </a>
    </div>
  </div>
</div>

// src/frontend/src/app/screens/profile/profile-header/profile-header.component.ts
import { Component, Input } from '@angular/core';

import { User } from '../../../models/user.model';
import { Session } from '../../../services/session.service';

@Component({
  selector: 'app-profile-header',
  templateUrl: './profile-header.component.html',
  styleUrls: ['./profile-header.component.scss']
})
export class ProfileHeaderComponent {
  @Input() user: User;

  constructor(private session: Session) {}

  isCurrentUser() {
    if (!this.user) {
      return false;
    }
    return this.session.userId() === this.user.id;
  }
}

@if (user) {
  <div class="glass-card w-full rounded-3xl p-6 sm:p-8 shadow-md border border-white/25 flex flex-col md:flex-row gap-6 md:gap-8 items-center md:items-start">
    <!-- Avatar Column -->
    <div class="relative w-24 h-24 sm:w-28 sm:h-28 rounded-full overflow-hidden border-4 border-primary/20 shadow-lg shrink-0">
      <img class="w-full h-full object-cover" [src]="user.avatar | image" [alt]="user.username">
    </div>
    <!-- Profile Details Column -->
    <div class="flex-grow flex flex-col items-center md:items-start text-center md:text-left gap-4 w-full">
      <div class="flex flex-wrap items-center justify-center md:justify-start gap-3.5 w-full">
        <h1 class="text-2xl sm:text-3xl font-black tracking-tight text-base-content">{{user.username}}</h1>
        @if (isCurrentUser()) {
          <div class="flex items-center gap-2">
            <a
              class="btn btn-outline btn-xs sm:btn-sm rounded-xl border-base-300 hover:bg-primary hover:border-primary hover:text-white font-bold transition-all"
              routerLink="/settings"
              >
              Edit Profile
            </a>
            <a
              class="btn btn-ghost btn-circle btn-xs sm:btn-sm text-base-content/65 hover:text-primary hover:bg-base-200"
              routerLink="/settings"
              title="Settings"
              >
              <fa-icon [icon]="['fas', 'cog']" class="text-sm"></fa-icon>
            </a>
          </div>
        }
      </div>
      <!-- Statistics Counters -->
      <div class="flex items-center gap-6 text-sm font-bold text-base-content/75 my-0.5">
        <span>
          <strong class="text-base-content font-black">{{user.images}}</strong> posts
        </span>
        <a
          [routerLink]="['/users', user.id, 'likes']"
          class="transition-colors hover:text-primary border-b border-dashed border-base-300 hover:border-primary pb-0.5"
          >
          Liked posts
        </a>
      </div>
      <!-- Bio Section -->
      <div class="flex flex-col gap-1 w-full max-w-xl">
        <h2 class="font-extrabold text-base text-base-content">{{user.name}}</h2>
        @if (user.bio) {
          <p class="text-sm text-base-content/75 whitespace-pre-wrap leading-relaxed">
            {{user.bio}}
          </p>
        }
      </div>
    </div>
  </div>
}
