// apps/frontend/src/lib/components/ProfileHeader.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import { Settings } from '@lucide/svelte';
  import { imageUrl } from '$lib/utils/imageUrl';
  import { pluralize } from '$lib/utils/pluralize';
  import type { User } from '$lib/types';

  let {
    profileUser = $bindable(),
    isCurrentUser,
    isFollowPending = $bindable(false)
  } = $props<{
    profileUser: User;
    isCurrentUser: boolean;
    isFollowPending?: boolean;
  }>();
</script>

<div class="flex w-full flex-col items-center gap-6 rounded-2xl border border-slate-200 bg-white p-6 text-slate-950 shadow-lg shadow-slate-900/5 dark:border-white/10 dark:bg-slate-950 dark:text-white sm:px-8 md:flex-row md:items-start">
  <div class="relative h-24 w-24 shrink-0 overflow-hidden rounded-full border border-slate-200 shadow-md dark:border-white/15 sm:h-28 sm:w-28">
    <img class="h-full w-full object-cover" src={imageUrl(profileUser.avatar)} alt={profileUser.username} />
  </div>

  <div class="flex w-full flex-grow flex-col gap-4 text-center md:text-left">
    <div class="flex w-full flex-col items-center gap-4 sm:flex-row sm:items-start sm:justify-between sm:text-left">
      <div class="grid min-w-0 gap-1">
        <h1 class="break-words text-2xl font-black tracking-tight text-slate-950 dark:text-white sm:text-3xl">
          {profileUser.name || profileUser.username}
        </h1>
        <p class="break-words text-sm font-bold text-slate-500 dark:text-slate-400">@{profileUser.username}</p>
      </div>

      {#if isCurrentUser}
        <a
          href="/settings"
          class="btn btn-sm inline-flex h-10 min-h-10 shrink-0 items-center justify-center gap-2 rounded-full border-0 bg-slate-950 px-5 font-extrabold leading-none text-white shadow-md shadow-slate-900/15 hover:bg-slate-800 dark:bg-white dark:text-slate-950 dark:hover:bg-slate-200"
        >
          <Settings class="h-4 w-4" />
          Settings
        </a>
      {:else}
        <form
          method="POST"
          action={profileUser.isFollowing ? '?/unfollow' : '?/follow'}
          use:enhance={() => {
            isFollowPending = true;
            const wasFollowing = profileUser.isFollowing;
            profileUser = { ...profileUser, isFollowing: !wasFollowing, followers: profileUser.followers + (wasFollowing ? -1 : 1) };
            return async ({ result }) => {
              isFollowPending = false;
              if (result.type === 'error' || result.type === 'failure') {
                profileUser = { ...profileUser, isFollowing: wasFollowing, followers: profileUser.followers + (wasFollowing ? 1 : -1) };
              }
            };
          }}
        >
          <button
            type="submit"
            disabled={isFollowPending}
            class="btn btn-sm inline-flex h-10 min-h-10 shrink-0 items-center justify-center gap-2 rounded-full border-0 px-5 font-extrabold leading-none shadow-md shadow-slate-900/15 transition-colors {profileUser.isFollowing ? 'bg-slate-200 text-slate-950 hover:bg-slate-300 dark:bg-white/20 dark:text-white dark:hover:bg-white/30' : 'bg-slate-950 text-white hover:bg-slate-800 dark:bg-white dark:text-slate-950 dark:hover:bg-slate-200'}"
          >
            {profileUser.isFollowing ? 'Unfollow' : 'Follow'}
          </button>
        </form>
      {/if}
    </div>

    {#if profileUser.bio}
      <p class="w-full max-w-xl whitespace-pre-wrap text-sm leading-relaxed text-slate-600 dark:text-slate-300">
        {profileUser.bio}
      </p>
    {/if}

    <div class="flex items-center justify-center gap-6 text-sm font-bold text-slate-600 dark:text-slate-300 md:justify-start">
      <a href="/@{profileUser.username}" class="transition-colors hover:text-slate-950 dark:hover:text-white">
        <strong class="font-black text-slate-950 dark:text-white">{profileUser.posts}</strong> {pluralize(profileUser.posts, 'post')}
      </a>
      <a href="/@{profileUser.username}/likes" class="transition-colors hover:text-slate-950 dark:hover:text-white">
        <strong class="font-black text-slate-950 dark:text-white">{profileUser.likes}</strong> {pluralize(profileUser.likes, 'like')}
      </a>
      <a href="/@{profileUser.username}/followers" class="transition-colors hover:text-slate-950 dark:hover:text-white">
        <strong class="font-black text-slate-950 dark:text-white">{profileUser.followers}</strong> {pluralize(profileUser.followers, 'follower')}
      </a>
      <a href="/@{profileUser.username}/following" class="transition-colors hover:text-slate-950 dark:hover:text-white">
        <strong class="font-black text-slate-950 dark:text-white">{profileUser.following}</strong> following
      </a>
    </div>
  </div>
</div>

// apps/frontend/src/app/features/users/pages/profile/profile-header/profile-header.component.ts
import {Component, inject, input, signal} from '@angular/core';
import {RouterLink} from '@angular/router';
import {LucideSettings} from '@lucide/angular';
import {finalize} from 'rxjs';

import {User} from '../../../models/user.model';
import {UserService} from '../../../services/user.service';
import {SessionService} from '../../../../auth/session.service';
import {ImagePipe} from '../../../../../shared/ui/pipes/image.pipe';
import {PluralizePipe} from '../../../../../shared/ui/pipes/pluralize.pipe';

@Component({
  selector: 'app-profile-header',
  templateUrl: './profile-header.component.html',
  standalone: true,
  imports: [RouterLink, ImagePipe, PluralizePipe, LucideSettings]
})
export class ProfileHeaderComponent {
  private session = inject(SessionService);
  private userService = inject(UserService);

  user = input.required<User>();
  isFollowPending = signal(false);

  isCurrentUser() {
    return this.session.userId() === this.user().id;
  }

  toggleFollow() {
    const user = this.user();
    if (this.isCurrentUser() || this.isFollowPending()) {
      return;
    }
    this.isFollowPending.set(true);

    if (user.isFollowing) {
      user.isFollowing = false;
      user.followers -= 1;
      this.userService.unfollowUser(user.id).pipe(
        finalize(() => this.isFollowPending.set(false))
      ).subscribe({
        error: () => {
          user.isFollowing = true;
          user.followers += 1;
        }
      });
    } else {
      user.isFollowing = true;
      user.followers += 1;
      this.userService.followUser(user.id).pipe(
        finalize(() => this.isFollowPending.set(false))
      ).subscribe({
        error: () => {
          user.isFollowing = false;
          user.followers -= 1;
        }
      });
    }
  }
}

<div class="flex w-full flex-col items-center gap-6 rounded-2xl border border-slate-200 bg-white p-6 text-slate-950 shadow-lg shadow-slate-900/5 dark:border-white/10 dark:bg-slate-950 dark:text-white sm:px-8 md:flex-row md:items-start">
  <div class="relative h-24 w-24 shrink-0 overflow-hidden rounded-full border border-slate-200 shadow-md dark:border-white/15 sm:h-28 sm:w-28">
    <img class="h-full w-full object-cover" [src]="user().avatar | image" [alt]="user().username">
  </div>
  <div class="flex w-full flex-grow flex-col gap-4 text-center md:text-left">
    <div class="flex w-full flex-col items-center gap-4 sm:flex-row sm:items-start sm:justify-between sm:text-left">
      <div class="grid min-w-0 gap-1">
        <h1 class="break-words text-2xl font-black tracking-tight text-slate-950 dark:text-white sm:text-3xl">{{user().name || user().username}}</h1>
        <p class="break-words text-sm font-bold text-slate-500 dark:text-slate-400">{{'@' + user().username}}</p>
      </div>
      @if (isCurrentUser()) {
        <a
          class="btn btn-sm inline-flex h-10 min-h-10 shrink-0 items-center justify-center gap-2 rounded-full border-0 bg-slate-950 px-5 font-extrabold leading-none text-white shadow-md shadow-slate-900/15 hover:bg-slate-800 dark:bg-white dark:text-slate-950 dark:hover:bg-slate-200"
          routerLink="/settings"
          >
          <svg lucideSettings class="h-4 w-4"></svg>
          Settings
        </a>
      } @else {
        <button
          class="btn btn-sm inline-flex h-10 min-h-10 shrink-0 items-center justify-center gap-2 rounded-full border-0 px-5 font-extrabold leading-none shadow-md shadow-slate-900/15 transition-colors"
          [class.bg-slate-950]="!user().isFollowing"
          [class.text-white]="!user().isFollowing"
          [class.hover:bg-slate-800]="!user().isFollowing"
          [class.dark:bg-white]="!user().isFollowing"
          [class.dark:text-slate-950]="!user().isFollowing"
          [class.dark:hover:bg-slate-200]="!user().isFollowing"
          [class.bg-slate-200]="user().isFollowing"
          [class.text-slate-950]="user().isFollowing"
          [class.hover:bg-slate-300]="user().isFollowing"
          [class.dark:bg-white/20]="user().isFollowing"
          [class.dark:text-white]="user().isFollowing"
          [class.dark:hover:bg-white/30]="user().isFollowing"
          (click)="toggleFollow()"
          [disabled]="isFollowPending()"
          >
          {{user().isFollowing ? 'Unfollow' : 'Follow'}}
        </button>
      }
    </div>

    @if (user().bio) {
      <p class="w-full max-w-xl whitespace-pre-wrap text-sm leading-relaxed text-slate-600 dark:text-slate-300">
        {{user().bio}}
      </p>
    }

    <div class="flex items-center justify-center gap-6 text-sm font-bold text-slate-600 dark:text-slate-300 md:justify-start">
      <span>
        <strong class="font-black text-slate-950 dark:text-white">{{user().posts}}</strong> {{user().posts | pluralize:'post'}}
      </span>
      <a
        [routerLink]="'/@' + user().username + '/likes'"
        class="transition-colors hover:text-slate-950 dark:hover:text-white"
        >
        <strong class="font-black text-slate-950 dark:text-white">{{user().likes}}</strong> {{user().likes | pluralize:'like'}}
      </a>
      <span>
        <strong class="font-black text-slate-950 dark:text-white">{{user().followers}}</strong> {{user().followers | pluralize:'follower'}}
      </span>
      <span>
        <strong class="font-black text-slate-950 dark:text-white">{{user().following}}</strong> following
      </span>
    </div>
  </div>
</div>
