// apps/frontend/src/app/features/users/pages/profile/thumbnail/thumbnail.component.ts
import {Component, input} from '@angular/core';
import {RouterLink} from '@angular/router';
import {LucideHeart} from '@lucide/angular';

import {Post} from '../../../../posts/models/post.model';
import {ImagePipe} from '../../../../../shared/ui/pipes/image.pipe';

@Component({
  selector: 'app-thumbnail',
  templateUrl: './thumbnail.component.html',
  standalone: true,
  imports: [RouterLink, ImagePipe, LucideHeart]
})
export class ThumbnailComponent {
  post = input.required<Post>();
}

<a [routerLink]="['/posts', post().publicId]" class="group relative block aspect-square w-full overflow-hidden rounded-2xl bg-base-300/30 border border-white/10 shadow-sm hover:shadow-md transition-all duration-500">
  <img
    class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-[1.04]"
    [src]="post().filename | image"
    [alt]="post().description"
    loading="lazy"
  >
  <div class="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 flex items-center justify-center transition-all duration-300 text-white font-extrabold text-sm gap-2 backdrop-blur-xs">
    <svg lucideHeart class="w-4 h-4 fill-current text-white"></svg>
    <span>{{post().likes}}</span>
  </div>
</a>

// apps/frontend/src/lib/components/Thumbnail.svelte
<script lang="ts">
  import { Heart } from '@lucide/svelte';
  import { imageUrl } from '$lib/utils/imageUrl';
  import type { Post } from '$lib/types';

  let { post }: { post: Post } = $props();
</script>

<a
  href="/posts/{post.publicId}"
  class="group relative block aspect-square w-full overflow-hidden rounded-2xl border border-white/10 bg-base-300/30 shadow-sm transition-all duration-500 hover:shadow-md"
>
  <img
    class="h-full w-full object-cover transition-transform duration-700 group-hover:scale-[1.04]"
    src={imageUrl(post.filename)}
    alt={post.description ?? ''}
    loading="lazy"
    width="300"
    height="300"
  />
  <div class="absolute inset-0 flex items-center justify-center gap-2 bg-black/40 text-sm font-extrabold text-white opacity-0 backdrop-blur-[2px] transition-all duration-300 group-hover:opacity-100">
    <Heart class="h-4 w-4 fill-current text-white" />
    <span>{post.likes}</span>
  </div>
</a>
