// apps/frontend-svelte/src/routes/(app)/settings/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import { ChevronRight } from '@lucide/svelte';
  import { theme } from '$lib/theme';

  type ThemeOption = 'light' | 'dark' | 'system';
  const options: ThemeOption[] = ['light', 'dark', 'system'];

  function optionTitle(opt: ThemeOption) {
    return opt.charAt(0).toUpperCase() + opt.slice(1);
  }

  function isActive(opt: ThemeOption) {
    return $theme === opt;
  }
</script>

<div class="mx-auto max-w-xl">
  <div class="rounded-2xl border border-slate-200 bg-white text-slate-950 dark:border-white/10 dark:bg-slate-950 dark:text-white flex w-full flex-col gap-6 p-6 shadow-lg shadow-slate-900/5 sm:px-8">
    <div class="grid gap-2 text-center sm:text-left">
      <h1 class="text-2xl font-black text-slate-950 dark:text-white">Settings</h1>
      <p class="text-xs text-slate-600 dark:text-slate-300">Manage your account settings, security and activity.</p>
    </div>

    <ul class="flex flex-col gap-3">
      <!-- Appearance -->
      <li class="rounded-2xl border border-slate-200 bg-slate-50 p-4 dark:border-white/10 dark:bg-white/5">
        <div class="flex flex-col gap-3">
          <div class="grid gap-2">
            <h2 class="text-sm font-bold text-slate-900 dark:text-slate-100">Appearance</h2>
            <p class="text-xs text-slate-600 dark:text-slate-400">Choose how PixelGram looks on this device.</p>
          </div>
          <div class="grid grid-cols-3 gap-2 rounded-full bg-white p-1 dark:bg-slate-950">
            {#each options as opt (opt)}
              <button
                type="button"
                class="h-10 rounded-full text-xs font-black transition-colors {isActive(opt) ? 'bg-slate-950 text-white shadow-md dark:bg-white dark:text-slate-950' : 'text-slate-600 hover:bg-slate-100 hover:text-slate-950 dark:text-slate-300 dark:hover:bg-white/10 dark:hover:text-white'}"
                onclick={() => theme.set(opt)}
              >
                {optionTitle(opt)}
              </button>
            {/each}
          </div>
        </div>
      </li>

      <!-- Edit Profile -->
      <li>
        <a
          href="/settings/profile"
          class="flex items-center justify-between rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm font-bold text-slate-900 transition-colors hover:border-slate-300 hover:bg-slate-100 dark:border-white/10 dark:bg-white/5 dark:text-slate-100 dark:hover:bg-white/10"
        >
          <span>Edit Profile</span>
          <ChevronRight class="h-4 w-4 text-slate-500 dark:text-slate-400" />
        </a>
      </li>

      <!-- Change Password -->
      <li>
        <a
          href="/settings/password"
          class="flex items-center justify-between rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm font-bold text-slate-900 transition-colors hover:border-slate-300 hover:bg-slate-100 dark:border-white/10 dark:bg-white/5 dark:text-slate-100 dark:hover:bg-white/10"
        >
          <span>Change Password</span>
          <ChevronRight class="h-4 w-4 text-slate-500 dark:text-slate-400" />
        </a>
      </li>

      <!-- Logout -->
      <li>
        <form method="POST" action="/logout" use:enhance>
          <button type="submit" class="btn btn-error btn-outline h-12 min-h-12 w-full rounded-full font-bold">
            Logout Account
          </button>
        </form>
      </li>
    </ul>
  </div>
</div>

// src/frontend/src/app/screens/settings/settings.component.ts
import {Component, inject} from '@angular/core';
import {Router, RouterLink} from '@angular/router';
import {NgClass} from '@angular/common';
import {LucideChevronRight} from '@lucide/angular';

import {APIClient} from '../../services/api-client.service';
import {SessionService} from '../../services/session.service';
import {ThemePreference, ThemeService} from '../../services/theme.service';

@Component({
  selector: 'app-settings',
  templateUrl: './settings.component.html',
  standalone: true,
  imports: [RouterLink, NgClass, LucideChevronRight]
})
export class SettingsComponent {
  private apiClient = inject(APIClient);
  private router = inject(Router);
  private session = inject(SessionService);
  theme = inject(ThemeService);

  userId() {
    return this.session.userId();
  }

  onLogoutClick() {
    this.apiClient.logoutUser().subscribe(() => {
      this.session.clear();
      this.router.navigate(['/']);
    });
  }

  setTheme(theme: ThemePreference) {
    this.theme.setPreference(theme);
  }
}

<div class="mx-auto max-w-md">
  <div class="flex w-full flex-col gap-5 rounded-2xl border border-slate-200 bg-white p-6 text-slate-950 shadow-lg shadow-slate-900/5 dark:border-white/10 dark:bg-slate-950 dark:text-white sm:p-8">
    <div class="mb-1 text-center sm:text-left">
      <h1 class="text-2xl font-black text-slate-950 dark:text-white">Settings</h1>
      <p class="mt-1 text-xs text-slate-600 dark:text-slate-300">Manage your account settings, security and activity.</p>
    </div>

    <ul class="flex flex-col gap-3">
      <li class="rounded-2xl border border-slate-200 bg-slate-50 p-4 dark:border-white/10 dark:bg-white/5">
        <div class="flex flex-col gap-3">
          <div>
            <h2 class="text-sm font-bold text-slate-900 dark:text-slate-100">Appearance</h2>
            <p class="mt-1 text-xs text-slate-600 dark:text-slate-400">Choose how PixelGram looks on this device.</p>
          </div>
          <div class="grid grid-cols-3 gap-2 rounded-full bg-white p-1 dark:bg-slate-950">
            @for (option of theme.options; track option) {
              <button
                type="button"
                class="h-10 rounded-full text-xs font-black transition-colors"
                [ngClass]="{
                  'bg-slate-950 text-white shadow-md dark:bg-white dark:text-slate-950': theme.optionActive(option),
                  'text-slate-600 hover:bg-slate-100 hover:text-slate-950 dark:text-slate-300 dark:hover:bg-white/10 dark:hover:text-white': !theme.optionActive(option)
                }"
                (click)="setTheme(option)"
              >
                {{ theme.optionTitle(option) }}
              </button>
            }
          </div>
        </div>
      </li>

      <li>
        <a 
          routerLink="/settings/profile" 
          class="flex items-center justify-between rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm font-bold text-slate-900 transition-colors hover:border-slate-300 hover:bg-slate-100 dark:border-white/10 dark:bg-white/5 dark:text-slate-100 dark:hover:bg-white/10"
        >
          <span class="flex items-center gap-2">Edit Profile</span>
          <svg lucideChevronRight class="h-4 w-4 text-slate-500 dark:text-slate-400"></svg>
        </a>
      </li>

      <li>
        <a 
          routerLink="/settings/password" 
          class="flex items-center justify-between rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm font-bold text-slate-900 transition-colors hover:border-slate-300 hover:bg-slate-100 dark:border-white/10 dark:bg-white/5 dark:text-slate-100 dark:hover:bg-white/10"
        >
          <span class="flex items-center gap-2">Change Password</span>
          <svg lucideChevronRight class="h-4 w-4 text-slate-500 dark:text-slate-400"></svg>
        </a>
      </li>

      <li class="mt-4">
        <button 
          (click)="onLogoutClick()" 
          class="btn btn-error btn-outline h-12 min-h-12 w-full rounded-full font-bold"
        >
          Logout Account
        </button>
      </li>
    </ul>
  </div>
</div>
